id: A3FC0DA4C
base_file: f7BAB.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:42:13.374226
  last_modified_at: 2022-06-17 11:42:13.374232
