id: A3FC0DA4C
base_file: f1B55.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:42:13.365086
  last_modified_at: 2022-06-17 11:42:13.365104
