id: A3FC0DA4C
base_file: fE523.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:42:13.377150
  last_modified_at: 2022-06-17 11:42:13.377155
